---

- block:
  - apt_key: url={{ pg_repositoty_key }} state=present
  - apt_repository: repo="{{ pg_repositoty }}" state=present
  - apt: name={{ item }} state=present
    with_items:
      - "postgresql-{{ pg_version }}"
      - "postgresql-server-dev-{{ pg_version }}"
    notify:
      - restart postgresql
  become: yes

- name: pg_hba_conf
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/{{ pg_version }}/main/pg_hba.conf
    force: yes
    backup: yes
  become: yes
  notify:
    - restart postgresql

- meta: flush_handlers
