---

- name: Generate locale
  command: /usr/sbin/locale-gen {{ locale }}

- name: Set locale
  command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }} LANGUAGE={{ language }}
  become: yes

- name: Set /etc/localtime
  command: /bin/cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime
  become: yes

- name: Set timezone (/etc/timezone)
  template: src=locale/timezone dest=/etc/timezone
  notify: update tzdata
  become: yes

- name: Install ntp packages
  apt: name=ntp state=present
  become: yes
