---

- block:
    - apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
    - apt_repository: repo="deb https://deb.nodesource.com/node_6.x trusty main" state=present
    - apt: name=nodejs state=present
  become: yes
